#!/bin/bash

# Cloudflare Pages 部署配置脚本
# 用法: ./setup-cloudflare-pages.sh

echo "🚀 Cloudflare Pages 部署配置"
echo "=============================="
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 登录 Cloudflare Dashboard: https://dash.cloudflare.com"
echo ""
echo "2. 点击左侧菜单 'Pages' → 'Create a project'"
echo ""
echo "3. 选择 'Connect to Git'"
echo ""
echo "4. 授权 GitHub，选择你的 image-bg-remover 仓库"
echo ""
echo "5. 构建设置："
echo "   - Framework preset: Next.js"
echo "   - Build command: npm run build"
echo "   - Build output directory: dist"
echo ""
echo "6. 环境变量（可选）："
echo "   - 如果用了 remove.bg API，添加 REMOVEBG_API_KEY"
echo ""
echo "7. 点击 'Save and Deploy'"
echo ""
echo "✅ 完成！以后每次 push 到 main 分支会自动部署"
echo ""
echo "📁 项目配置已准备好："
echo "   - next.config.ts (静态导出配置)"
echo "   - package.json (Next.js 项目)"
echo ""
